/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_IME_ID */

#ifndef _Included_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_IME_ID
#define _Included_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_IME_ID
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
