/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kika_qwt9_inputmethod_Resource_qwt9ini */

#ifndef _Included_kika_qwt9_inputmethod_Resource_qwt9ini
#define _Included_kika_qwt9_inputmethod_Resource_qwt9ini
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_Free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1Free
  (JNIEnv *, jclass);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_Initial
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1Initial
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jobject);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_Initial_Py
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/StringBuilder;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1Initial_1Py
        (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jstring, jstring, jobject);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetGrouping
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;II[Lkika/qwt9/inputmethod/Resource/CandidatesInfo;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetGrouping
  (JNIEnv *, jclass, jobject, jstring, jint, jint, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetCandidateCount
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;ZI)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetCandidateCount
  (JNIEnv *, jclass, jobject, jstring, jboolean, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetCandidates
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;ZIII[Lkika/qwt9/inputmethod/Resource/CandidatesInfo;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetCandidates
  (JNIEnv *, jclass, jobject, jstring, jboolean, jint, jint, jint, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_AddPhrase
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1AddPhrase
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_RemovePhrase
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1RemovePhrase
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_LearnWord
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1LearnWord
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_LearnWordEx
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1LearnWordEx
  (JNIEnv *, jclass, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_LearnWordUpdate
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1LearnWordUpdate
  (JNIEnv *, jclass, jobject, jstring, jstring, jboolean, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_LearnWordSaveAs
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1LearnWordSaveAs
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring, jboolean, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetNextWordCandidates
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;II[Lkika/qwt9/inputmethod/Resource/CandidatesInfo;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetNextWordCandidates
  (JNIEnv *, jclass, jobject, jstring, jint, jint, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_DeleLearnedWord
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1DeleLearnedWord
  (JNIEnv *, jclass, jobject, jstring, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_ResetLearnedWordFromFile
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1ResetLearnedWordFromFile
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_DeleLearnedWordFrom
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1DeleLearnedWordFrom
  (JNIEnv *, jclass, jobject, jstring, jstring, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_MultiTap_Input
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1MultiTap_1Input
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetSelectedCandidateCode
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetSelectedCandidateCode
        (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_SetOption
 * Signature: (Lkika/qwt9/inputmethod/Resource/OPTION_ID;Lkika/qwt9/inputmethod/Resource/KEYBD_MODE;)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1SetOption
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_InitialDictionary
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1InitialDictionary
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_IsVocabularyExist
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1IsVocabularyExist
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_WordExist
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1WordExist
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_AppendVocabulary
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1AppendVocabulary
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_DeleteVocabulary
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1DeleteVocabulary
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_IsLearnWordExist
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1IsLearnWordExist
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetLearnedWordFromFile
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;I[Lkika/qwt9/inputmethod/Resource/CandidatesInfo;)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetLearnedWordFromFile
  (JNIEnv *, jclass, jobject, jstring, jint, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetComposingText
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetComposingText
  (JNIEnv *, jclass, jobject, jstring, jint, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_NMapKoreanCode
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;Z)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1NMapKoreanCode
  (JNIEnv *, jclass, jobject, jstring, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_NMapKeyCode
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1NMapKeyCode
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_KeyCodeNMap
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1KeyCodeNMap
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_ShiftKeyCode
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1ShiftKeyCode
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_GetVirtualKeybdLayout
 * Signature: (Lkika/qwt9/inputmethod/Resource/qwt9ini/IQQI_IME_ID;Z)[[Ljava/lang/Integer;
 */
JNIEXPORT jobjectArray JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1GetVirtualKeybdLayout
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    IQQI_Version
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_IQQI_1Version
  (JNIEnv *, jclass);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    createOnMemoryKikaNative
 * Signature: (JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_createOnMemoryKikaNative
  (JNIEnv *, jclass, jlong, jstring, jobjectArray, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    openKikaNative
 * Signature: (Ljava/lang/String;JJZ)J
 */
JNIEXPORT jlong JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_openKikaNative
  (JNIEnv *, jclass, jstring, jlong, jlong, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getHeaderInfoKikaNative
 * Signature: (J[I[ILjava/util/ArrayList;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getHeaderInfoKikaNative
  (JNIEnv *, jclass, jlong, jintArray, jintArray, jobject, jobject);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    flushKikaNative
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_flushKikaNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    needsToRunGCKikaNative
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_needsToRunGCKikaNative
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    flushWithGCKikaNative
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_flushWithGCKikaNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    closeKikaNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_closeKikaNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getFormatVersionKikaNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getFormatVersionKikaNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getProbabilityKikaNative
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getProbabilityKikaNative
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getMaxProbabilityOfExactMatchesKikaNative
 * Signature: (J[I)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getMaxProbabilityOfExactMatchesKikaNative
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getNgramProbabilityKikaNative
 * Signature: (J[[I[Z[I)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getNgramProbabilityKikaNative
  (JNIEnv *, jclass, jlong, jobjectArray, jbooleanArray, jintArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getWordPropertyKikaNative
 * Signature: (J[IZ[I[Z[ILjava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getWordPropertyKikaNative
  (JNIEnv *, jclass, jlong, jintArray, jboolean, jintArray, jbooleanArray, jintArray, jobject, jobject, jobject, jobject, jobject, jobject);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getNextWordKikaNative
 * Signature: (JI[I[Z)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getNextWordKikaNative
  (JNIEnv *, jclass, jlong, jint, jintArray, jbooleanArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    addUnigramEntryKikaNative
 * Signature: (J[II[IIZZZI)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_addUnigramEntryKikaNative
  (JNIEnv *, jclass, jlong, jintArray, jint, jintArray, jint, jboolean, jboolean, jboolean, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    removeUnigramEntryKikaNative
 * Signature: (J[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_removeUnigramEntryKikaNative
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    addNgramEntryKikaNative
 * Signature: (J[[I[Z[III)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_addNgramEntryKikaNative
  (JNIEnv *, jclass, jlong, jobjectArray, jbooleanArray, jintArray, jint, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    removeNgramEntryKikaNative
 * Signature: (J[[I[Z[I)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_removeNgramEntryKikaNative
  (JNIEnv *, jclass, jlong, jobjectArray, jbooleanArray, jintArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    updateEntriesForWordWithNgramContextKikaNative
 * Signature: (J[[I[Z[IZII)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_updateEntriesForWordWithNgramContextKikaNative
  (JNIEnv *, jclass, jlong, jobjectArray, jbooleanArray, jintArray, jboolean, jint, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getPropertyKikaNative
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getPropertyKikaNative
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    isCorruptedKikaNative
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_isCorruptedKikaNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    migrateKikaNative
 * Signature: (JLjava/lang/String;J)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_migrateKikaNative
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    setDicTraverseSessionKikaNative
 * Signature: (Ljava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_setDicTraverseSessionKikaNative
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    initDicTraverseSessionKikaNative
 * Signature: (JJ[II)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_initDicTraverseSessionKikaNative
  (JNIEnv *, jclass, jlong, jlong, jintArray, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    releaseDicTraverseSessionKikaNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_releaseDicTraverseSessionKikaNative
  (JNIEnv *, jclass, jlong);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    getSuggestionsKikaNative
 * Signature: (JJJ[I[I[I[I[II[IZ[[I[I[ZI[I[I[I[I[I[I[F)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_getSuggestionsKikaNative
  (JNIEnv *, jclass, jlong, jlong, jlong, jintArray, jintArray, jintArray, jintArray, jintArray, jint, jintArray, jboolean, jobjectArray, jintArray, jbooleanArray, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jintArray, jfloatArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    createEmptyDictFileKikaNative
 * Signature: (Ljava/lang/String;JLjava/lang/String;[Ljava/lang/String;[Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_createEmptyDictFileKikaNative
  (JNIEnv *, jclass, jstring, jlong, jstring, jobjectArray, jobjectArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    calcNormalizedScoreKikaNative
 * Signature: ([I[II)F
 */
JNIEXPORT jfloat JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_calcNormalizedScoreKikaNative
  (JNIEnv *, jclass, jintArray, jintArray, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    setCurrentTimeForTestKikaNative
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_setCurrentTimeForTestKikaNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    setProximityInfoKikaNative
 * Signature: (IIIIII[II[I[I[I[I[I[F[F[F)J
 */
JNIEXPORT jlong JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_setProximityInfoKikaNative
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jintArray, jint, jintArray, jintArray, jintArray, jintArray, jintArray, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     kika_qwt9_inputmethod_Resource_qwt9ini
 * Method:    releaseProximityInfoKikaNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_kika_qwt9_inputmethod_Resource_qwt9ini_releaseProximityInfoKikaNative
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
